const deck: Card[] = [
	{ value: 14, suit: 'h', key: 'Ah' },
	{ value: 13, suit: 'h', key: 'Kh' },
	{ value: 12, suit: 'h', key: 'Qh' },
	{ value: 11, suit: 'h', key: 'Jh' },
	{ value: 10, suit: 'h', key: 'Th' },
	{ value: 9, suit: 'h', key: '9h' },
	{ value: 8, suit: 'h', key: '8h' },
	{ value: 7, suit: 'h', key: '7h' },
	{ value: 6, suit: 'h', key: '6h' },
	{ value: 5, suit: 'h', key: '5h' },
	{ value: 4, suit: 'h', key: '4h' },
	{ value: 3, suit: 'h', key: '3h' },
	{ value: 2, suit: 'h', key: '2h' },
	{ value: 14, suit: 'd', key: 'Ad' },
	{ value: 13, suit: 'd', key: 'Kd' },
	{ value: 12, suit: 'd', key: 'Qd' },
	{ value: 11, suit: 'd', key: 'Jd' },
	{ value: 10, suit: 'd', key: 'Td' },
	{ value: 9, suit: 'd', key: '9d' },
	{ value: 8, suit: 'd', key: '8d' },
	{ value: 7, suit: 'd', key: '7d' },
	{ value: 6, suit: 'd', key: '6d' },
	{ value: 5, suit: 'd', key: '5d' },
	{ value: 4, suit: 'd', key: '4d' },
	{ value: 3, suit: 'd', key: '3d' },
	{ value: 2, suit: 'd', key: '2d' },
	{ value: 14, suit: 'c', key: 'Ac' },
	{ value: 13, suit: 'c', key: 'Kc' },
	{ value: 12, suit: 'c', key: 'Qc' },
	{ value: 11, suit: 'c', key: 'Jc' },
	{ value: 10, suit: 'c', key: 'Tc' },
	{ value: 9, suit: 'c', key: '9c' },
	{ value: 8, suit: 'c', key: '8c' },
	{ value: 7, suit: 'c', key: '7c' },
	{ value: 6, suit: 'c', key: '6c' },
	{ value: 5, suit: 'c', key: '5c' },
	{ value: 4, suit: 'c', key: '4c' },
	{ value: 3, suit: 'c', key: '3c' },
	{ value: 2, suit: 'c', key: '2c' },
	{ value: 14, suit: 's', key: 'As' },
	{ value: 13, suit: 's', key: 'Ks' },
	{ value: 12, suit: 's', key: 'Qs' },
	{ value: 11, suit: 's', key: 'Js' },
	{ value: 10, suit: 's', key: 'Ts' },
	{ value: 9, suit: 's', key: '9s' },
	{ value: 8, suit: 's', key: '8s' },
	{ value: 7, suit: 's', key: '7s' },
	{ value: 6, suit: 's', key: '6s' },
	{ value: 5, suit: 's', key: '5s' },
	{ value: 4, suit: 's', key: '4s' },
	{ value: 3, suit: 's', key: '3s' },
	{ value: 2, suit: 's', key: '2s' },
]

type Card = {
	suit: string
	value: number
	key: string
}

export default deck
